--DROP SCHEMA public;

--CREATE SCHEMA public AUTHORIZATION postgres;

-- DROP SEQUENCE public.bodega_id_bodega_seq;

CREATE SEQUENCE public.bodega_id_bodega_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
COMMENT ON SEQUENCE bodega_id_bodega_seq IS 'DbWrench Autogenerated Sequence.';
-- DROP SEQUENCE public.categoria_producto_id_categoria_producto_seq;

CREATE SEQUENCE public.categoria_producto_id_categoria_producto_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
COMMENT ON SEQUENCE categoria_producto_id_categoria_producto_seq IS 'DbWrench Autogenerated Sequence.';
-- DROP SEQUENCE public.detalle_pedido_id_detalle_pedido_seq;

CREATE SEQUENCE public.detalle_pedido_id_detalle_pedido_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
COMMENT ON SEQUENCE detalle_pedido_id_detalle_pedido_seq IS 'DbWrench Autogenerated Sequence.';
-- DROP SEQUENCE public.estado_trazabilidad_id_estado_trazabilidad_seq;

CREATE SEQUENCE public.estado_trazabilidad_id_estado_trazabilidad_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
COMMENT ON SEQUENCE estado_trazabilidad_id_estado_trazabilidad_seq IS 'DbWrench Autogenerated Sequence.';
-- DROP SEQUENCE public.productos_bodega_id_producto_bodega_seq;

CREATE SEQUENCE public.productos_bodega_id_producto_bodega_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
COMMENT ON SEQUENCE productos_bodega_id_producto_bodega_seq IS 'DbWrench Autogenerated Sequence.';
-- DROP SEQUENCE public.productos_id_producto_seq;

CREATE SEQUENCE public.productos_id_producto_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
COMMENT ON SEQUENCE productos_id_producto_seq IS 'DbWrench Autogenerated Sequence.';
-- DROP SEQUENCE public.productos_preveedores_id_producto_proveedor_seq;

CREATE SEQUENCE public.productos_preveedores_id_producto_proveedor_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
COMMENT ON SEQUENCE productos_preveedores_id_producto_proveedor_seq IS 'DbWrench Autogenerated Sequence.';
-- DROP SEQUENCE public.proveedores_id_proveedor_seq;

CREATE SEQUENCE public.proveedores_id_proveedor_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
COMMENT ON SEQUENCE proveedores_id_proveedor_seq IS 'DbWrench Autogenerated Sequence.';
-- DROP SEQUENCE public.tipo_producto_id_tipo_producto_seq;

CREATE SEQUENCE public.tipo_producto_id_tipo_producto_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
COMMENT ON SEQUENCE tipo_producto_id_tipo_producto_seq IS 'DbWrench Autogenerated Sequence.';
-- DROP SEQUENCE public.trazabilidad_id_trazabilidad_seq;

CREATE SEQUENCE public.trazabilidad_id_trazabilidad_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
COMMENT ON SEQUENCE trazabilidad_id_trazabilidad_seq IS 'DbWrench Autogenerated Sequence.';-- public.bodega definition

-- Drop table

-- DROP TABLE public.bodega;

CREATE TABLE public.bodega (
	id_bodega serial4 NOT NULL,
	descripcion varchar(40) NOT NULL,
	CONSTRAINT pkbodega PRIMARY KEY (id_bodega)
);


-- public.categoria_producto definition

-- Drop table

-- DROP TABLE public.categoria_producto;

CREATE TABLE public.categoria_producto (
	id_categoria_producto serial4 NOT NULL,
	descripcion varchar(40) NOT NULL,
	CONSTRAINT pkcategoria_producto PRIMARY KEY (id_categoria_producto)
);


-- public.estado_trazabilidad definition

-- Drop table

-- DROP TABLE public.estado_trazabilidad;

CREATE TABLE public.estado_trazabilidad (
	id_estado_trazabilidad serial4 NOT NULL,
	descripcion varchar(40) NOT NULL,
	CONSTRAINT pkestado_trazabilidad PRIMARY KEY (id_estado_trazabilidad)
);


-- public.pedidos definition

-- Drop table

-- DROP TABLE public.pedidos;

CREATE TABLE public.pedidos (
	id_pedido int4 NOT NULL,
	fecha_ingreso timestamp NOT NULL,
	fecha_recibido timestamp NULL,
	CONSTRAINT pkpedidos PRIMARY KEY (id_pedido)
);


-- public.proveedores definition

-- Drop table

-- DROP TABLE public.proveedores;

CREATE TABLE public.proveedores (
	id_proveedor serial4 NOT NULL,
	rut_proveedor varchar(10) NOT NULL,
	razon_social varchar(40) NOT NULL,
	CONSTRAINT pkproveedores PRIMARY KEY (id_proveedor)
);


-- public.tipo_producto definition

-- Drop table

-- DROP TABLE public.tipo_producto;

CREATE TABLE public.tipo_producto (
	id_tipo_producto serial4 NOT NULL,
	descripcion int4 NOT NULL,
	CONSTRAINT pktipo_producto PRIMARY KEY (id_tipo_producto)
);


-- public.productos definition

-- Drop table

-- DROP TABLE public.productos;

CREATE TABLE public.productos (
	id_producto serial4 NOT NULL,
	descripcion varchar(40) NOT NULL,
	categoria_producto_id int4 NULL,
	tipo_producto_id int4 NULL,
	CONSTRAINT pkproductos PRIMARY KEY (id_producto),
	CONSTRAINT fk_productos_categoria_producto FOREIGN KEY (categoria_producto_id) REFERENCES public.categoria_producto(id_categoria_producto),
	CONSTRAINT fk_productos_tipo_producto FOREIGN KEY (tipo_producto_id) REFERENCES public.tipo_producto(id_tipo_producto)
);


-- public.productos_bodega definition

-- Drop table

-- DROP TABLE public.productos_bodega;

CREATE TABLE public.productos_bodega (
	id_producto_bodega serial4 NOT NULL,
	producto_id int4 NULL,
	bodega_id int4 NULL,
	stock int4 NOT NULL,
	CONSTRAINT pkproductos_bodega PRIMARY KEY (id_producto_bodega),
	CONSTRAINT fk_productos_bodega_bodega FOREIGN KEY (bodega_id) REFERENCES public.bodega(id_bodega),
	CONSTRAINT fk_productos_bodega_productos FOREIGN KEY (producto_id) REFERENCES public.productos(id_producto)
);


-- public.productos_preveedores definition

-- Drop table

-- DROP TABLE public.productos_preveedores;

CREATE TABLE public.productos_preveedores (
	id_producto_proveedor serial4 NOT NULL,
	producto_id int4 NOT NULL,
	proveedor_id int4 NOT NULL,
	CONSTRAINT pkproductos_preveedores PRIMARY KEY (id_producto_proveedor),
	CONSTRAINT fk_productos_preveedores_productos FOREIGN KEY (producto_id) REFERENCES public.productos(id_producto),
	CONSTRAINT fk_productos_preveedores_proveedores FOREIGN KEY (proveedor_id) REFERENCES public.proveedores(id_proveedor)
);


-- public.trazabilidad definition

-- Drop table

-- DROP TABLE public.trazabilidad;

CREATE TABLE public.trazabilidad (
	id_trazabilidad serial4 NOT NULL,
	pedido_id int4 NOT NULL,
	fecha_inicio_preparacion timestamp NULL,
	fecha_fin_preparacion timestamp NULL,
	fecha_estimada_envio date NULL,
	fecha_envio timestamp NULL,
	fecha_recibido timestamp NULL,
	codigo_trazabilidad varchar(40) NULL,
	trazabilidad_estado_id int4 NOT NULL,
	CONSTRAINT pktrazabilidad PRIMARY KEY (id_trazabilidad),
	CONSTRAINT fk_trazabilidad_estado_trazabilidad FOREIGN KEY (trazabilidad_estado_id) REFERENCES public.estado_trazabilidad(id_estado_trazabilidad),
	CONSTRAINT fk_trazabilidad_pedidos FOREIGN KEY (pedido_id) REFERENCES public.pedidos(id_pedido)
);


-- public.detalle_pedido definition

-- Drop table

-- DROP TABLE public.detalle_pedido;

CREATE TABLE public.detalle_pedido (
	id_detalle_pedido serial4 NOT NULL,
	proveedor_producto_id int4 NOT NULL,
	pedido_id int4 NOT NULL,
	cantidad int4 NOT NULL DEFAULT 1,
	CONSTRAINT pkdetalle_pedido PRIMARY KEY (id_detalle_pedido),
	CONSTRAINT fk_detalle_pedido_pedidos FOREIGN KEY (pedido_id) REFERENCES public.pedidos(id_pedido),
	CONSTRAINT fk_detalle_pedido_productos_preveedores FOREIGN KEY (proveedor_producto_id) REFERENCES public.productos_preveedores(id_producto_proveedor)
);
